include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
linter:
  rules:
    sort_constructors_first: true
    unnecessary_await_in_return: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
