include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
linter:
  rules:
    unnecessary_await_in_return: false
    flutter_style_todos: false
